---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver
  namespace: airflow
  annotations:
    source_url: "https://github.com/bogdan-rizac/airflow-dags.git/kube"
data:
  webserver-secret-key: MmY2NGVhMzBkOGY3NDQ0MTAyY2ZhMWEwZDA1ZmE1NWQK
